adobe/aepsdk-target-ios

.circleci/config.yml, Makefile, Script/codecov_downloader.sh
=> check SHASUM for codecov script file

Script/codecov_downloader.sh
=> update codecov step

.circleci/config.yml, .github/workflows/release.yml, AEPTarget.podspec, AEPTarget.xcodeproj/project.pbxproj, AEPTarget/Sources/TargetConstants.swift, Makefile, Package.swift, README.md, Script/codecov_downloader.sh, Script/test-SPM.sh
Prepare for AEPTarget v3.1.0 release. This PR also includes the prev Codecov fixes and doc updates
=> Prepare for release + other updates

AEPTarget/Sources/Target.swift, AEPTarget/Sources/TargetRequest.swift, Documentation/AEPTarget.md, Script/test-SPM.sh, Script/test-podspec.sh
- Updated git API reference for the new TargetRequest constructor + other doc fixes
- Updated the scripts. test-SPM now uses swift tools version 5.1 instead of 5.3
- Send click A4T event once we can be almost sure that Target click notification will go through.
=> Doc updates + minor fix

.circleci/config.yml, AEPTarget.xcodeproj/project.pbxproj, AEPTarget/Sources/Target.swift, AEPTarget/Sources/TargetConstants.swift, AEPTarget/Sources/TargetDeliveryRequest.swift, AEPTarget/Sources/TargetDeliveryRequestBuilder.swift, AEPTarget/Tests/FunctionalTests/TargetFunctionalTests.swift, AEPTarget/Tests/FunctionalTests/TargetFunctionalTestsBase.swift, AEPTarget/Tests/TestHelpers/MockPreviewManager.swift, Makefile, Podfile, Podfile.lock, README.md
Ref: [mOB-15329]
- Added missing preview functionality, along with functional test updates
- Fixed make archive issues (specify SwiftLint as pod dependency)
- Added support for dSym generation upon make archive
=> Target preview support & misc updates

AEPTarget.podspec, AEPTarget.xcodeproj/project.pbxproj, AEPTarget/Sources/TargetConstants.swift, Makefile, README.md
=> Release prep v3.1.2

.circleci/config.yml, AEPTarget.podspec, AEPTarget.xcodeproj/project.pbxproj, AEPTarget/Sources/Target.swift, AEPTarget/Sources/TargetConstants.swift, AEPTarget/Sources/TargetDeliveryRequest.swift, AEPTarget/Sources/TargetDeliveryRequestBuilder.swift, AEPTarget/Tests/FunctionalTests/TargetFunctionalTests.swift, AEPTarget/Tests/FunctionalTests/TargetFunctionalTestsBase.swift, AEPTarget/Tests/TestHelpers/MockPreviewManager.swift, Makefile, Podfile, Podfile.lock, README.md
=> dev -> main (v3.1.2)

AEPTarget.podspec, AEPTarget.xcodeproj/project.pbxproj, AEPTarget/Sources/TargetConstants.swift, AEPTarget/Sources/TargetDeliveryRequestBuilder.swift, AEPTarget/Tests/FunctionalTests/TargetDisplayedLocationsFunctionalTests.swift, AEPTarget/Tests/FunctionalTests/TargetFunctionalTestsBase.swift, AEPTarget/Tests/IntegrationTests/TargetIntegrationTests.swift, AEPTarget/Tests/TestHelpers/TestableExtensionRuntime.swift, AEPTarget/Tests/UnitTests/DeliveryRequestBuilderTests.swift, Podfile.lock, README.md
=> dev -> main (v3.1.3)

AEPTarget/Sources/Target+PublicAPI.swift, Documentation/AEPTarget.md
=> Target doc updates

AEPTarget.podspec, AEPTarget.xcodeproj/project.pbxproj, AEPTarget/Sources/Event+Target.swift, AEPTarget/Sources/Target+PublicAPI.swift, AEPTarget/Sources/Target.swift, AEPTarget/Sources/TargetConstants.swift, AEPTarget/Sources/TargetError.swift, AEPTarget/Tests/FunctionalTests/TargetRawRequestsFunctionalTests.swift, AEPTargetDemoApp/ContentView.swift, AEPTargetDemoObjCApp/Base.lproj/Main.storyboard, AEPTargetDemoObjCApp/ViewController.m, README.md
=> Target release prep + misc fixes

Documentation/AEPTarget.md
=> Updated docs for Target Raw APIs

AEPTarget.podspec, AEPTarget.xcodeproj/project.pbxproj, AEPTarget/Sources/Target.swift, AEPTarget/Sources/TargetConstants.swift, AEPTargetDemoApp/AppDelegate.swift, Podfile.lock, README.md
* Enable preview by default if not enabled via configuration
* Updated the Target SDK version
=> dev -> main (v3.3.1)

Script/test-SPM.sh
=> Fixed SPM test script 

Documentation/AEPTarget.md, Script/test-SPM.sh
=> Fixed SPM PIF generation issue

.circleci/config.yml, .github/workflows/release.yml, .swiftlint.yml, AEPTarget.podspec, AEPTarget.xcodeproj/project.pbxproj, AEPTarget/Sources/Target+PublicAPI.swift, AEPTarget/Sources/Target.swift, AEPTarget/Sources/TargetConstants.swift, AEPTarget/Sources/TargetState.swift, AEPTarget/Tests/UnitTests/DeliveryRequestBuilderTests.swift, Makefile, Package.swift, Podfile, Podfile.lock, README.md, Script/test-SPM.sh, Script/test-podspec.sh
=> dev to staging for v4.0.0

.circleci/config.yml, .github/workflows/release.yml, .swiftlint.yml, AEPTarget.podspec, AEPTarget.xcodeproj/project.pbxproj, AEPTarget/Sources/Target+PublicAPI.swift, AEPTarget/Sources/Target.swift, AEPTarget/Sources/TargetConstants.swift, AEPTarget/Sources/TargetState.swift, AEPTarget/Tests/UnitTests/DeliveryRequestBuilderTests.swift, Makefile, Package.swift, Podfile, Podfile.lock, README.md, Script/test-SPM.sh, Script/test-podspec.sh
=> staging to main for v4.0.0

AEPTarget.podspec, AEPTarget.xcodeproj/project.pbxproj, AEPTarget/Sources/Target.swift, AEPTarget/Sources/TargetConstants.swift, AEPTarget/Tests/IntegrationTests/TargetIntegrationTests.swift
Fix for bug where Target Response with JSON Array content were rejected
=> Release version 4.0.1 -  Staging to Main

AEPTarget/Sources/Target.swift, AEPTarget/Sources/TargetConstants.swift, AEPTarget/Tests/IntegrationTests/TargetIntegrationTests.swift, Podfile.lock
The X-EXC-SDK header will contain SDK info in the format
AdobeTargetMobile-iOS<-wrapper-friendly-name> e.g. AdobeTargetMobile-iOS, AdobeTargetMobile-iOS-Flutter etc
=> X-EXC-SDK support for Target requests

AEPTarget.podspec
=> -update version in podspec

AEPTarget.podspec, AEPTarget.xcodeproj/project.pbxproj, AEPTarget/Sources/Target.swift, AEPTarget/Sources/TargetConstants.swift, AEPTarget/Tests/FunctionalTests/TargetFunctionalTests.swift, AEPTarget/Tests/FunctionalTests/TargetFunctionalTestsBase.swift, AEPTarget/Tests/FunctionalTests/TargetMigrationFunctionalTests.swift, AEPTarget/Tests/IntegrationTests/TargetIntegrationTests.swift, AEPTarget/Tests/TestHelpers/NamedCollectionDataStore+clear.swift, AEPTarget/Tests/TestHelpers/TargetTestConstants.swift, AEPTarget/Tests/TestHelpers/UserDefaults+clear.swift, AEPTarget/Tests/UnitTests/TargetStateTests.swift, AEPTarget/Tests/UnitTests/TargetTests.swift, AEPTarget/Tests/UnitTests/TargetV4MigratorTests.swift, AEPTarget/Tests/UnitTests/TargetV5MigratorTests.swift, AEPTargetDemoApp/ContentView.swift, Documentation/AEPTarget.md, Podfile.lock
=> Target SDK should attach response tokens in the retrieveLocationContent data callback

AEPTarget.podspec, AEPTarget.xcodeproj/project.pbxproj, AEPTarget/Sources/Target.swift, AEPTarget/Sources/TargetConstants.swift, AEPTarget/Tests/FunctionalTests/TargetFunctionalTests.swift, AEPTarget/Tests/FunctionalTests/TargetFunctionalTestsBase.swift, AEPTarget/Tests/FunctionalTests/TargetMigrationFunctionalTests.swift, AEPTarget/Tests/IntegrationTests/TargetIntegrationTests.swift, AEPTarget/Tests/TestHelpers/NamedCollectionDataStore+clear.swift, AEPTarget/Tests/TestHelpers/TargetTestConstants.swift, AEPTarget/Tests/TestHelpers/UserDefaults+clear.swift, AEPTarget/Tests/UnitTests/TargetStateTests.swift, AEPTarget/Tests/UnitTests/TargetTests.swift, AEPTarget/Tests/UnitTests/TargetV4MigratorTests.swift, AEPTarget/Tests/UnitTests/TargetV5MigratorTests.swift, AEPTargetDemoApp/ContentView.swift, Documentation/AEPTarget.md, Podfile.lock
=> staging to main (v4.0.3)

AEPTarget.podspec
=> -update max dependency version in podspec

AEPTarget.podspec, AEPTarget.xcodeproj/project.pbxproj, AEPTarget/Sources/TargetConstants.swift, AEPTarget/Tests/TestHelpers/TargetTestConstants.swift
=> promote 4.0.4 to main

.circleci/config.yml, README.md
=> -fix circle config
